

const Privacy = () => {
   return (
      <div className="container xl:px-11 my-20">
         <div className="top_txt text-center ">
            <h1 className="mb-3">PRIVACY POLICY AND YOUR PRIVACY RIGHTS </h1>
            <h3 className="font-normal mb-11">Last revised on August 12, 2021 </h3>
         </div>
         <div className="privacytxt text-lg">
            <p>Thank you for visiting screendollars.com, a destination for information about movies and the film industry. </p>
            <p>Screendollars LLC and its Affiliates (“Screendollars,” “we,” “us,” or “our”) operate news, entertainment, and informational websites and digital products and services. In this Privacy Policy, “Affiliates” refers to subsidiaries and entities in which Screendollars or its subsidiaries operate or have an ownership interest. </p>
            <p>This Privacy Policy applies only to the information Screendollars and its Affiliates collect through the websites, mobile applications, electronic devices, kiosks, and all other digital products and services we provide, any other services that display this Privacy Policy, and all of the associated content, functionalities and advertising (collectively, the “Services”). This Privacy Policy governs the Services regardless of how you access them. Some Services may have a specific, separate privacy policy that will govern use of those Services. This Privacy Policy describes: </p>
            <ol className="pl-5">
               <li>the information we collect and how we collect it; </li>
               <li>what we do with the information we collect; </li>
               <li>how we share and disclose user information with third parties; </li>
               <li>Screendollars’ use of online analytics and tailored advertising;</li>
               <li> how you can access and update your information;</li>
               <li>how we protect information;</li>
               <li>linked sites and advertisements;</li>
               <li>collection of certain information by third parties through our Services;</li>
               <li>use of the Services by users from outside the United States;</li>
               <li>use of the Services by children;</li>
               <li>how to contact us;</li>
               <li>no rights of third parties; and</li>
               <li> changes to this Privacy Policy. </li>
            </ol>
            <h2 className="mt-8 mb-4">1 - The information we collect and how we collect it </h2>
            <p>How we collect and store information depends on the Services you use. You can use some of the Services without providing any information other than that automatically collected as described below. </p>
            <h3>1.1 Information you provide </h3>
            <p>We may collect information about you during your use of the Services, including but not limited to your name, username, password, email address, postal address, phone number, mobile phone number, payment information, gender, birth year, and information you provide or post on our Services or allow us to access, such as photos, video and/or audio, when you do certain things, such as: </p>
            <ul>
               <li>enter registration information for one or more of our Services; </li>
               <li>make a purchase; </li>
               <li>request certain features (e.g., newsletters, updates, and other products); </li>
               <li>connect with the Services or otherwise allow us to access certain information about you via a social networking site (SNS);</li>
               <li>post user-generated content, including comments, to or on any of our Services; </li>
               <li>navigate our websites; or </li>
               <li>submit your information to us for any other reason. </li>
            </ul>
            <p>We may collect and store your user ID associated with an SNS account that you use to sign in to your Screendollars account or connect or use with the Services. When you sign in to your Screendollars account or mobile application with your SNS account information or otherwise connect to your SNS account with the Services, you authorize Screendollars to collect, store, and use in accordance with this Privacy Policy any and all information available to Screendollars through the SNS interface, including without limitation any information that you have made public in connection with your SNS account, information that the SNS shares with us, or information that is disclosed as being shared during the sign-in process. Please be careful and responsible whenever you are online. Should you choose to voluntarily disclose information through the Services, such as via an SNS, on message boards, in chat areas or in advertising or notices you post, that information can be viewed publicly and may be collected and used by third parties without our knowledge (or our consent) and may result in data collection by or unsolicited messages from other individuals or third parties. </p>
            <h3 className="mb-4">1.2 Automatically-collected information </h3>
            <h3>1.2.1 Device/usage information </h3>
            <p>We may automatically collect certain information about the computer or devices (including mobile devices) you use to access the Services. For example, we may collect and analyze information such as (a) IP addresses, geolocation information (as described in the next section below), unique device identifiers including mobile advertising identifiers and other information about your mobile phone or other mobile device(s), browser types, browser language, operating system, the state or country from which you accessed the Services; and (b) information related to the ways in which you interact with the Services, such as: referring and exit pages and URLs, platform type, clicked items, interaction with advertisements, domain names, landing pages, pages and content viewed and the order of those pages, the amount of time spent on particular pages, mouse hover including location and time spent on each area of the page, the date and time you used the Services, the frequency of your use of the Services, error logs, and other similar information. As described further below, we may use third-party analytics providers and technologies, including cookies and similar tools, to assist in collecting and analyzing this information. </p>
            <p>We may also capture other data, such as search criteria and results. In some cases, we will associate this information with a unique Screendollars identifier for our internal use, in which case your Screendollars identifier will be considered Screendollars information, and nothing in this Privacy Policy restricts how Screendollars may use this information. </p>
            <h3>1.2.2 Location information</h3>
            <p>We may collect different types of information about your location, including general information (e.g., IP address, ZIP code) and more specific information (e.g., GPS-based functionality on mobile devices used to access the Services), and may use that information to customize the Services with location-based information, advertising, and features. For example, if your IP address indicates an origin in downtown Los Angeles, the Services may be customized with downtown Los Angeles-specific information and advertisements. To do this, your location information may be shared with our agents, vendors or advertisers. If you access the Services through a mobile device and you do not want your device to provide us with location-tracking information, you can disable the GPS or other location-tracking functions on your device, provided your device allows you to do this. See your device manufacturer’s instructions for further details. </p>
            <h3>1.2.3 Cookies and other electronic technologies</h3>
            <p>When you use the Services, we use persistent and session cookies and other similar tracking technologies to: (a) store your username and password; (b) monitor and analyze the usage of our sites and Services by collecting the information discussed in section 1.2.1 above; (c) customize the Services to your explicit and inferred preferences; and (d) tailor advertising displayed by the Services, as well as advertisements that may be displayed on other websites or mobile applications. We along with our vendors may also use other Internet technologies, such as Flash technologies, Web beacons or pixel tags, and other similar technologies, to deliver or communicate with cookies and track your use of the Services, as well as serve you ads and personalize/customize your experience when you are using our Services and/or when you are on other websites when those cookies can be accessed. We also may include Web beacons in email messages, newsletters and other electronic communications to determine whether the message has been opened and for other analytics, personalization and advertising. As we adopt additional technologies, we may also gather additional information through other methods. </p>
            <p>We may sometimes target ads to you through ‘onboarded’ audiences: to do this, we may share information you have provided to us with service providers, who will de-identify the information and associate it with cookies that enable us to reach you with display media. We may also help these service providers place their own cookies, by deploying a cookie that is associated with a ‘hashed’ value associated with interest-based or demographic data, to permit advertising to be directed to you on other websites, applications or services. </p>
            <p>Most browsers automatically accept cookies, but you can modify your browser setting to decline cookies by visiting the Help portion of your browser’s toolbar. If you choose to decline cookies, please note that you may not be able to sign in, customize, or use some of the interactive features of the Services, and the advertisements you see may not be as relevant to you. We may also use Flash cookies. Flash cookies operate differently than browser cookies, and cookie management tools available in a web browser will not remove Flash cookies. To learn more about how to manage Flash cookies, you can visit the <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html" target="_blank">Adobe website</a> and make changes at the <a href="https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager02.html" target="_blank">Global Privacy Settings Panel</a>. Please note that limiting third-party cookies through your browser controls will not necessarily opt you out of first- or third-party interestbased advertising, as some technologies (including those we or our partners may use) may not respond to these browser controls. </p>
            <p>To opt-out of interest-based advertising that is enabled by many industry platforms and providers (including much of the advertising described in this section), please see the choices we have described in Section 4.2, in particular the DAA’s opt-out page. </p>
            <h3>1.3 Information from third parties </h3>
            <p>We may obtain additional information about you from third parties such as marketers, partners, researchers, social networks, data services companies (e.g., for data enhancement) and others. We may combine information that we collect from you with information about you that we obtain from such third parties and information derived from any other subscription, product, or service we provide. </p>
            <h3>1.4 Collection of information across personal devices, and applications </h3>
            <p>Sometimes, we (or our service providers) may use the information we collect – for instance, log-in credentials, IP addresses, hashed email addresses, and unique mobile device identifiers – to locate or try to locate the same unique users across multiple browsers or devices (such as smartphones, tablets, or computers), or work with providers that do this, in order to better tailor content, features, and advertising, and provide you with a seamless experience across the devices you use to access the Services. </p>
            <h2 className="mt-8 mb-4">2 - What we do with the information we collect </h2>
            <p>We use the information that we collect for the following purposes: </p>
            <ul>
               <li>for the purposes for which you provided it; </li>
               <li>to send you information about your relationship or transactions with us; </li>
               <li>to send you alerts or other communications via SMS messages or other media or networks; </li>
               <li>to notify you about new features of the Services, special events, or products, services, and special offers; </li>
               <li>to administer sweepstakes and contests; </li>
               <li>to process and respond to your inquiries; </li>
               <li>to contact you with information that we believe will be of interest to you; </li>
               <li>to attribute content that you make available through the Services; </li>
               <li>to generate and review reports and data about our user base and usage patterns of the Services; </li>
               <li>to perform analytics and research aimed at improving the accuracy, effectiveness, usability, or popularity of the Services; </li>
               <li>to offer, manage, monitor and improve the content and features of the Services or develop new Services; </li>
               <li>to allow us to personalize or otherwise provide the content and advertising that you see on the Services and on other websites and mobile applications and to understand how users interact with and use our advertisements and Services; </li>
               <li>to enforce the legal terms that govern your use of the Services; </li>
               <li>to administer and troubleshoot the Services; </li>
               <li>to associate your activities, customize content or tailor advertising across different devices and browsers that you use to access the Services (for instance, computers, tablets, mobile devices, applications and websites); and </li>
               <li>to send you offers and advertisements through various channels (which may include, for instance, display, email, direct mail, and TV), whether on our behalf or on behalf of marketing partners with whom we may engage. </li>
            </ul>
            <p>The Services are supported by advertising revenue. We may send you commercial emails on behalf of ourselves, our Affiliates, and advertisers. Each such email we send you will have an opt-out that you can use to stop receiving such communications. </p>
            <h2 className="mt-8 mb-4">3 - How we share and disclose user information with third parties </h2>
            <p>We may make your information available to other companies, websites, applications or people in the circumstances described below: </p>
            <p>We may rent, sell, or share your information with non-affiliated third parties: (a) to provide services or products that you have requested; (b) when we have your permission; or (c) as described in this Privacy Policy. </p>
            <p>We may share your information with any agent or company that is part of Screendollars to provide the Services or advertising or to communicate with you on our behalf. </p>
            <p>We may provide access to or share your information with select third parties who perform services on our behalf. These third parties provide a variety of services to us, including without limitation billing, sales, marketing, provision of content and features, advertising, analytics, research, customer service, shipping and fulfillment, data storage, security, fraud prevention, payment processing, and legal services. When you sign up to participate in a contest or sweepstakes, your information may also be provided to our sweepstakes or contest advertisers, operators, or sponsors and the use of that information will be also governed by those advertisers’, operators’, or sponsors’ privacy policies or practices. </p>
            <p>We may share your information with third parties for their own and sometimes our own advertising and marketing purposes, with whom we have a contractual relationship, including without limitation third-party advertisers and advertising and list brokering networks. </p>
            <p>We may access, disclose, transfer and preserve your information when we have a good faith belief that doing so is necessary to: </p>
            <ul>
               <li>protect our users and our legal rights, privacy or safety, and that of our subsidiaries, Affiliates, employees, agents, contractors, or other individuals, including by enforcing this Privacy Policy or any applicable Screendollars Terms of Service; </li>
               <li>comply with the law including with subpoenas, search warrants, court orders, and other legal processes; and respond to inquiries or requests from government, regulatory bodies, law enforcement, public authorities, or content protection organizations;  </li>
               <li>permit us to pursue available remedies, commence, participate in, or defend litigation, or limit the damages that we may sustain; </li>
               <li>enforce this Privacy Policy or any applicable Screendollars Terms of Service. </li>
            </ul>
            <p>We may share your information in connection with any proposed or actual merger, reorganization, transfer of control, a sale of some or all Screendollars assets, or a financing or acquisition of all or a portion of our business by another company. We may aggregate and we may de-identify information collected by the Services or via other means so that the information is not intended to identify you. Our use and disclosure of aggregated and/or deidentified information is not subject to any restrictions under this Privacy Policy, and we may disclose it to others without limitation for any purpose. </p>
            <h2 className="mt-8 mb-4">4 - Screendollars’ use of online analytics and tailored advertising </h2>
            <h3>4.1 Online analytics</h3>
            <p>We may use third-party web analytics services on our Services, such as those of Google Analytics, Adobe Omniture, and similar providers. These service providers use the sort of technology described in Section 1.2 to help us analyze how users use the Services, including by noting the third-party website from which you arrive. The information (including your IP address) collected by the technology will be disclosed to or collected directly by these service providers, who use the information to evaluate your use of the Services. We also use Google Analytics for certain purposes related to advertising, as described in the following section. To prevent Google Analytics from using your information for analytics, you may install the Google Analytics Opt-out Browser Add-on by <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">clicking here.</a> </p>
            <h2 className="mt-8 mb-4">4.2 Tailored advertising </h2>
            <p>When you use the Services, Screendollars may serve you with ads based on various factors such as the content of the page you are visiting, information you provide such as your age or gender, your searches, demographic and geographic data, user-generated content and other information that you provide to us. These ads may be based on your current activity or your activity over time and may be tailored to your interests. </p>
            <p>Also, third parties, including without limitation those whose products or services are accessible or advertised via the Services, may place cookies or other tracking technologies (such as mobile ‘SDKs,’ which function like a mobile version of a browser cookie and are embedded in mobile applications) on your computer browser, mobile phone applications, or other device to collect information about your use of the Services to (i) inform, optimize, and serve ads based on past visits to our websites and other sites and mobile applications and (ii) report how our ad impressions, other uses of ad services, and interactions with these ad impressions and ad services are related to visits to our websites, mobile applications, and use of our Services. We also allow other third parties (e.g., ad networks and ad servers such as Google AdSense, DoubleClick and others) to serve tailored ads to you on the Services, and to access their own cookies or other tracking technologies on your computer, mobile phone, or other device you use to access the Services so that tailored ads may be delivered to you when you are using other websites and mobile applications. We also may share with third-party advertisers a hashed version of your email address, which may be identified by a service provider for purposes of delivering tailored advertising on the Services, other websites, and/or mobile applications. </p>
            <p>We neither have access to, nor does this Privacy Policy govern, the use of cookies or other tracking technologies that may be placed on your computer, mobile phone, or other device you use to access the Services by nonaffiliated, third-party ad technology, ad servers, ad networks or any other nonaffiliated third parties. Those parties that use these technologies may offer you a way to opt-out of ad targeting as described below. If you are interested in more information about tailored browser advertising and how you can generally control cookies from being put on your computer to deliver interestbased advertising, you may visit the <a href="https://www.networkadvertising.org/choices" target="_blank">Network Advertising Initiative’s Consumer Opt-Out link,</a>the <a href="https://www.aboutads.info/choices/" target="_blank"> Digital Advertising Alliance’s (DAA’s) Consumer Opt-Out link</a> or <a href="https://preferences-mgr.truste.com/" target="_blank"> TrustArc’s Advertising Choices Page</a> TrustArc’s Advertising Choices Page  to opt-out of receiving tailored advertising from companies that participate in those programs. You may also use the links available in advertisements that appear in the Services and learn more about our advertising practices through the About Our Ads link that may be available through the Services. </p>
            <p>If you have a Google account, we may use Google Analytics to display advertising to you. You can opt-out of Google Analytics for display advertising or customize Google display network ads by visiting the <a href="https://www.google.com/settings/ads" target="_blank">Google Ads Settings </a>page.  You will need to log in to Google via the Sign In link if you are not already logged in when you visit that page. </p>
            <p> Please note that to the extent advertising technology is integrated into the Services, you may still receive advertisements even if you opt-out of tailored advertising. In that case, the ads will just not be tailored. </p>
            <p>You can also opt-out of ‘cross-app’ advertising -- interest-based advertising that is associated with your use of our or other mobile applications. To do so, please go to your device settings and opt-out through the controls provided through Google/Android or iOS, as applicable. Each operating system, iOS for Apple phones, Android for Android devices and Windows for Microsoft devices provides its own instructions on how to prevent the delivery of tailored in-application advertisements. (We cannot guarantee that these instructions will not change, or that they will continue to be available; they are controlled by each mobile platform, not us.). For any other devices and/or operating systems, please visit the privacy settings for the applicable device or contact the applicable platform operator. </p>
            <p>We likewise may work with platform providers who serve advertising across devices. For instance, we may want to reach our web-based customers when they are on their mobile devices. This is done, generally, by correlating common attributes (such as IP addresses, other browser or device information or hashed email addresses) across devices, to infer a common identity across multiple channels. To opt-out of this type of advertising, you can do so by opting out of each separate device or browser, as we have described above. </p>
            <h2 className="mt-8 mb-4">5 - How you can access and update your information </h2>
            <p>To ensure that you have some control over the information we have about you, you may review and update certain user profile information by logging in to the relevant portions of the Services where such information may be updated (may be available on some Services and not others) or by contacting us at contactus@screendollars.com. </p>
            <h2 className="mt-8 mb-4">6 - How we protect information</h2>
            <p>We have implemented a variety of administrative, technical, and physical security measures to protect against the unauthorized access, destruction or alteration of your information. These safeguards vary based on the sensitivity of the information that we collect, process and store and the current state of technology. </p>
            <p>Although we take appropriate measures to safeguard against unauthorized disclosures of information, we cannot guarantee that information that we collect will never be disclosed in a manner that is inconsistent with this Privacy Policy.  </p>
            <h2 className="mt-8 mb-4">7 - Linked sites and advertisements </h2>
            <p>The Services may contain links to third-party websites. We are not responsible for the privacy practices or the content of those third-party websites. </p>
            <p>We have relationships with third-party providers to provide content, products, services, and functionality through the Services. When you visit sites or use any Services provided in conjunction with one or more of these third-party providers and the brands of those providers appear on the site or Services in connection with such content, products, services, or functionalities, we may share any information you provide or that is collected during your use of those Services with those providers. </p>
            <h2 className="mt-8 mb-4">8 - Collection of certain information by third parties through our Services </h2>
            <p>For certain advertising that appears in the Services, an advertiser may request, and you may directly provide to that advertiser, information such as your name, home address, or email address. When you provide information in that way, the information you submit may be used by the advertiser in any way that it chooses, including to market to you, or to share with others. The information may be covered by the advertiser’s separate privacy policy, but in many cases that will not be the case because the advertiser may have no separate online presence. You should therefore only submit your information in these cases when you are comfortable doing so given the above conditions, and if you have any questions about the privacy practices of an advertiser, you should contact the advertiser itself. </p>
            <h2 className="mt-8 mb-4">9 - Use of the Services by users from outside the United States </h2>
            <p>The Services are hosted in the United States and locations outside the United States and are governed by United States law. If you are using the Services from outside the United States, please be aware that your information may be transferred to, stored and processed in the United States and other countries where our servers are located and our databases are operated. The data protection and other laws of the United States and other countries might not be as comprehensive or protective of certain rights as those in your country. Under United States law, your information may be subject to access requests from governments, courts, or law enforcement in the United States. By using the Services, you consent to your information being transferred to our facilities and to the facilities of those third parties with whom we share it as described in this Privacy Policy and processed in those facilities. </p>
            <h2 className="mt-8 mb-4">10 - Use of the Services by children</h2>
            <p>The Services are not intended for persons under the age of 13; however, we are providing some family content during this time of the COVID-19 crisis for parents or guardians who are home with their kids. We shall obtain the consent of a parent or guardian to the extent that the parent’s or guardian’s child under 13 submits personal information to us in connection with such family content. We will retain the information only so long as reasonably necessary to: (1) publish the family content with the consent of the parent(s) or guardian(s); (2) fulfill the request or allow the child to participate in the family content or activity; (3) ensure the security of our users and our online services; and/or (4) as required by law. On the specific pages that contain family content in our online Services, we may also offer family activities such as puzzles and games for children under the age of 13, which only collect persistent identifiers to support the services. Our other games offerings are not intended for use by children under the age of 13. If we learn we have collected personal information from a child in a manner inconsistent with legal requirements, we will either delete the personal information or seek consent from parents or guardians. A parent or guardian may contact contactus@screendollars.com to review personal information provided by the parent’s or guardian’s child, have such information deleted, and/or refuse to allow further collection or use of such information. </p>
            <h2 className="mt-8 mb-4">11. How to contact us </h2>
            <p>If you have any questions, comments, or concerns regarding this Privacy Policy, please send an email to <a href="mailto:contactus@screendollars.com">contactus@screendollars.com</a> or written correspondence to Screendollars, 33 Miller Hill Road, Dover, MA 02030. </p>
            <h2 className="mt-8 mb-4">12. No rights of third parties</h2>
            <p>This Privacy Policy does not create rights enforceable by third parties. </p>
            <h2 className="mt-8 mb-4">13. Changes to this Privacy Policy </h2>
            <p>Screendollars reserves the right to change this Privacy Policy at any time to reflect changes in the law, our data collection and use practices, the features of our Services, or advances in technology. Please check this page periodically for changes. Your continued use of the Services following the posting of changes to this Privacy Policy will mean you accept those changes. </p>
            <p className="mt-6">Copyright © 2021 Screendollars LLC </p>
         </div>
      </div>
   )
}

export default Privacy

