import Pagetitle from "@/components/Products/Pagetitle"

const ProjectionDetail = () => {
  return (
    <div className="projectiondetial">
      <Pagetitle heading={"Memorial Weekend Box Office Swims To Solid Results"} disc="This week, Paul and Mike discuss the dominance of THE LITTLE MERMAID over Memorial Day weekend, and the importance of having a diverse slate of films...including four other notable newcomers... together with the holdovers, representing collectively a 'something for everybody' lineup of films in the Top 10." />
        <div className="container">
           <div className="projectionvid">
              <iframe src="https://www.youtube.com/embed/v6t49khetOA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
           </div>
           <h5>Transcript :</h5>
           <div className="textareatranspile">
            <p>
               Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor. Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor. Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor.
               Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor. Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor. Etiam Convallis Elementum Sapien, A Aliquam Turpis Aliquam Vitae. Praesent Sollicitudin Felis Vel Mi Facilisis Posuere. Nulla Ultrices Facilisis Justo, Non Varius Nisl Semper Vel. Interdum Et Malesuada Fames Ac Ante Ipsum Primis In Faucibus. Phasellus At Ante Mattis, Condimentum Velit Et, Dignissim Nunc. Integer Quis Tincidunt Purus. Duis Dignissim Mauris Vel Elit Commodo, Eu Hendrerit Leo Ultrices. Nulla Vehicula Vestibulum Purus At Rutrum. Pellentesque Habitant Morbi Tristique Senectus Et Netus Et Malesuada Fames Ac Turpis Egestas. Curabitur Dignissim Massa Nec Libero Scelerisque Rutrum. Curabitur Ac Purus Id Elit Hendrerit Lacinia. Nullam Sit Amet Sem Efficitur, Porta Diam In, Convallis Tortor.
            </p>
           </div>
        </div>
    </div>
  )
}

export default ProjectionDetail